#! /usr/bin/env python3

from typing import List, Tuple
import os


def convert_async_to_sync(filename_async: str, filename_sync: str,
                          repl: List[Tuple[str, str]], delete_lines: List[str]):
    
    dt_mod_async = os.path.getmtime(filename_async)
    dt_mod_script = os.path.getmtime(__file__)
    try:
        dt_mod_sync = os.path.getmtime(filename_sync)
    except:
        dt_mod_sync = 0
    
    if dt_mod_async < dt_mod_sync and dt_mod_script < dt_mod_sync:
        return
    
    lines: list = []
    with open(filename_async, 'r') as file:
        for line in file:
            line_s: str = line.strip()
            keep: bool = True
            for t in delete_lines:
                if t == line_s:
                    print(f'Deleted line: {t}')
                    keep = False
                    break
            if keep:
                lines.append(line)
    
    f_sync: str = ''.join(lines)
    t: Tuple[str, str]
    index: int
    for t in repl:
        index = f_sync.find(t[0])
        if index >= 0:
            f_sync = f_sync.replace(t[0], t[1])
        else:
            print(f'No match for rule: {t[0]} -> {t[1]}')

    with open(filename_sync, 'w') as file:
        file.write(f_sync)

    os.system(f'autopep8 -i {filename_sync}')


if True:
    _files: List[Tuple[str, str]] = [('aio_odoorpc_base/aio/__init__.py', 'aio_odoorpc_base/sync/__init__.py'),
                                     ('aio_odoorpc_base/aio/rpc.py', 'aio_odoorpc_base/sync/rpc.py'),
                                     ('aio_odoorpc_base/aio/common.py', 'aio_odoorpc_base/sync/common.py'),
                                     ('aio_odoorpc_base/aio/db.py', 'aio_odoorpc_base/sync/db.py'),
                                     ('aio_odoorpc_base/aio/object.py', 'aio_odoorpc_base/sync/object.py')]

    _delete_lines: List[str] = ['from inspect import isawaitable',
                                'if isawaitable(data):',
                                'data = await data']
    
    _comment_lines: List[str] = []

    _repl: List[Tuple[str, str]] = [('from aio_odoorpc_base.aio', 'from aio_odoorpc_base.sync'),
                                    ('T_AsyncResponse', 'T_Response'),
                                    ('T_AsyncHttpClient', 'T_HttpClient'),
                                    ('async def', 'def'),
                                    ('await ', '')]
    
    f: Tuple[str, str]
    for f in _files:
        convert_async_to_sync(f[0], f[1], _repl, _delete_lines)
