from aio_odoorpc_base.aio_jsonrpc import aio_jsonrpc, aio_check_jsonrpc_response, aio_login, aio_execute_kw
from aio_odoorpc_base.jsonrpc import jsonrpc, check_jsonrpc_response, login, execute_kw
from aio_odoorpc_base.helpers import odoo_base_url2jsonrpc_endpoint, build_odoo_jsonrpc_endpoint_url
